import Layout from '../components/layout/layout';
import "./delivery_payment.css";
function DeliveryPayment() {
    return (
        <>
            <Layout>
                <div className='main-delivery-container'>
                    <div className='content'>
                        <div className='payment-container'>
                            <h1>PAYMENT POLICY</h1>
                            <div className='payment-container-content'>
                                <h2>CURRENCIES</h2>
                                <p>ALL PAYMENTS AND REFUNDS FOR SHIPMENTS ARE INVOICED IN EURO (EUR).</p>
                                <p>CREDIT CARDS WILL BE DEBITED IN EURO, THEREFORE, DUE TO EXCHANGE RATES, THE FINAL PRICE WILL BE CALCULATED IN THE APPLICABLE EXCHANGE RATE ON THE DAY THE TRANSACTION IS PROCESSED BY THE CREDIT CARD COMPANY.</p>
                                <h2>PAYMENT METHODS</h2>
                                <h3>VERITEVESTMENTS.STORE ACCEPTS PAYMENT BY CREDIT CARD OR DEBIT CARD</h3>
                                <p>WHEN CLIENTS PLACE ORDERS ONLINE, CREDIT DETAILS ARE FORWARDED TO A PROTECTED ONLINE BANKING SYSTEM PROVIDED BY BANCA SELLA WHICH ACCEPTS MASTERCARD, VISA, VISA DELTA, VISA DEBIT, AMERICAN EXPRESS, ELECTRON.</p>
                                <p>FIRST USE CUSTOMERS PAYING BY CREDIT CARD MAY FACE A SLIGHT DELAY IN CHARGES DUE TO AN AUTHENTICATION PROCESS THAT TAKES PLACE. IN SUCH CASES, THE RECEIPT AND FINAL CONFIRMATION OF THE ORDER WILL BE SENT TO THE CUSTOMER AFTER APPROVAL FROM THE BANK.</p>
                                <p>FOR PRE-ORDER PURCHASES, CREDIT CARDS ARE DEBITED AT THE MOMENT THE ORDER IS PLACED. PRE-ORDER PRODUCTS THAT ARE PURCHASED BY BANK TRANSFER MUST BE PAID FOR WITHIN 48 HOURS OF PLACING THE ORDER, AS STATED IN THE BANK TRANSFER GUIDELINES ABOVE.</p>
                            </div>
                        </div>
                        <div className='delivery-container'>
                            <h1>SHIPPING AND DELIVERY POLICY</h1>
                            <div className="delivery-container-content">
                                <h2>DELIVERY TIME AND COST</h2>
                                <p>ALL ORDERS ARE TYPICALLY PROCESSED WITHIN 1 WORKING DAY AND SHIPPED VIA DHL EXPRESS GO GREEN. HOWEVER, AT TIMES SUCH AS DURING SALE SEASONS, ORDERS MIGHT SUFFER A SLIGHT DELAY DUE TO THE HIGHER VOLUME OF ORDERS BEING PROCESSED. IN THE CASE OF A NON-STANDARD VOLUME SHIPMENT, WE RESERVE THE RIGHT TO CONTACT THE CLIENT FOR PAYMENT OF ADDITIONAL SHIPMENT COSTS THAT MAY ARISE. VERITEVESTMENTS.EU WILL NOT BE HELD RESPONSIBLE FOR ANY DELAY IN SHIPMENT CAUSED BY WEATHER CONDITIONS, INTERNATIONAL CUSTOMS ISSUES OR ANY OTHER CIRCUMSTANCES BEYOND THE CONTROL OF VERITE VESTMENTS.</p>
                                <p>VERITEVESTMENTS.EU DDP (DELIVERY DUTIES PAID) SHIPPING TO A FEW SELECTED COUNTRIES AND REGIONS. THIS MEANS TAXES, CUSTOM FEES AND IMPORT FEES FOR EUROPEAN UNION COUNTRIES, SWITZERLAND, THE UNITED KINGDOM, THE UNITED STATES, CHINA MAINLAND, HONG KONG SAR, JAPAN AND SOUTH KOREA ARE INCLUDED. SHIPMENTS TO COUNTRIES NOT LISTED ABOVE WILL BE SHIPPED DDU (DELIVERY DUTIES UNPAID) WHICH MEANS THEY MAY BE SUBJECT TO CUSTOM FEES, IMPORT FEES AND TAXES, THESE ARE THE SOLE RESPONSIBILITY OF THE CLIENT AND WILL NOT BE BORNE OR REIMBURSED BY VERITE VESTMENTS.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </Layout>
        </>
    );
}

export default DeliveryPayment;