export const product = [
    {
        "id": 152,
        "Category": "Jeans",
        "Title": "VETEMENTS",
        "Name": "Black Convertible Cargo Pants",
        "Description": "Cotton twill cargo pants. Cargo pockets throughout.",
        "Featured": "| Belt loops" + "| Cinch tabs at waistband" + "| Four-pocket styling" + "| Zip-fly" + "| Detachable zip panel at legs" + "| D-ring straps at front and back waistband",
        "Material": "100% cotton",
        "MadeIn": "Made in Italy",
        "Price": 1450.00,
        "Image": "/images/jeans1.jpg",
        "Image2": "/images/jeans1_1.webp",
        "Image3": "/images/jeans1_2.webp",
        "Image4": "/images/jeans1_3.webp",
    },
    {
        "id": 131,
        "Category": "Jeans",
        "Title": "VETEMENTS",
        "Name": "Blue Destroyed Jeans",
        "Description": "Non-stretch denim jeans. Distressing and fading throughout.",
        "Featured": "| Belt loops" + "| Five-pocket styling" + "| Button-fly" + "| Extended cuffs" + "| Logo patch at back waistband" + "Supplier color: Light blue",
        "Material": "100% cotton",
        "MadeIn": "Made in Italy",
        "Price": 1450.00,
        "Image": "/images/jeans3.webp",
        "Image2": "/images/jeans3_1.webp",
        "Image3": "/images/jeans3_2.webp",
        "Image4": "/images/jeans3_3.webp",
    },
    {
        "id": 174,
        "Category": "Jeans",
        "Title": "VETEMENTS",
        "Name": "Blue Embroidered Baggy Jeans",
        "Description": "Wide-leg non-stretch denim jeans. Fading throughout.",
        "Featured": "| Belt loops" + "| Five-pocket styling" + "| Button-fly" + "| Logo embroidered at front" + "| Leather logo patch at back waistband" + "| Contrast stitching in tan" + " Supplier color: Light blue",
        "Material": "100% cotton",
        "MadeIn": "Made in Italy",
        "Price": 1410.00,
        "Image": "/images/jeans2.webp",
        "Image2": "/images/jeans2_1.webp",
        "Image3": "/images/jeans2_2.webp",
        "Image4": "/images/jeans2_3.webp",
    },
    {
        "id": 183,
        "Category": "Jeans",
        "Title": "VETEMENTS",
        "Name": "Black Destroyed Jeans",
        "Description": "Loose-fit non-stretch denim jeans. Distressing throughout",
        "Featured": "| Belt loops" + "| Five-pocket styling" + "| Button-fly" + "| Rips at front legs" + "| Leather logo patch at back waistband" + "| Logo flag at back pocket" + " Supplier color: Black",
        "Material": "100% cotton",
        "MadeIn": "Made in Italy",
        "Price": 1300.00,
        "Image": "/images/jeans4.webp",
        "Image2": "/images/jeans4_1.webp",
        "Image3": "/images/jeans4_2.webp",
        "Image4": "/images/jeans4_3.webp",
    },
    {
        "id": 166,
        "Category": "Jeans",
        "Title": "VETEMENTS",
        "Name": "Black Baggy Jeans",
        "Description": "Loose-fit non-stretch denim jeans.",
        "Featured": "| Belt loops" + "| Five-pocket styling" + "| Button-fly" + "|      " + "| Logo flag at back pocket" + "| Logo-engraved bronze-tone hardware" + " Supplier color: Black",
        "Material": "100% cotton",
        "MadeIn": "Made in Italy",
        "Price": 1290.00,
        "Image": "/images/jeans5.webp",
        "Image2": "/images/jeans5_1.webp",
        "Image3": "/images/jeans5_2.webp",
        "Image4": "/images/jeans5_3.webp",
    },
    {
        "id": 144,
        "Category": "Jeans",
        "Title": "VETEMENTS",
        "Name": "Blue Baggy Jeans",
        "Description": "Loose-fit non-stretch denim jeans. Fading throughout|",
        "Featured": "| Belt loops" + "| Five-pocket styling" + "| Button-fly" + "| Leather logo patch at back waistband" + "| Logo flag at back pocket" + "| Logo-engraved bronze-tone hardware" + " Supplier color: Light Blue",
        "Material": "100% cotton",
        "MadeIn": "Made in Italy",
        "Price": 1290.00,
        "Image": "/images/jeans6.webp",
        "Image2": "/images/jeans6_1.webp",
        "Image3": "/images/jeans6_2.jpg",
        "Image4": "/images/jeans6_3.webp",
    },
    {
        "id": 244,
        "Category": "Shorts",
        "Title": "RICK OWENS",
        "Name": "Black Boxer Shorts",
        "Description": "Garment-dyed GOTS-certified cotton jersey shorts." ,
        "Featured": "| Drawstring at elasticized waistband" + "| Two-pocket styling" + "| Raw edge at cuffs" + "| Vented outseams" + "Supplier color: Black",
        "Material": "100% cotton",  
        "MadeIn": "Made in Italy",
        "Price": 455.00,
        "Image": "/images/shorts1.webp",
        "Image2": "/images/shorts1_1.webp",
        "Image3": "/images/shorts1_2.webp",
        "Image4": "/images/short1_3.webp",
    },
    {
        "id": 245,
        "Category": "Shorts",
        "Title": "RICK OWENS",
        "Name": "Black Strobe Chaps",
        "Description": "Heavyweight CORDURA® nylon canvas chaps." ,
        "Featured":"| Wrap construction" + "| Single-pocket styling" + "| Integrated press-release webbing belt" + "| Zip pockets and utility pocket" + "| Press-stud fastening at leg" + "| Fully lined" + "Part of the Rick Owens BONOTTO collection." + "Supplier color: Black",
        "Material": "100% cotton",
        "MadeIn": "Made in Italy",
        "Price": 720.00,
        "Image": "/images/shorts2.webp",
        "Image2": "/images/shorts2_1.webp",
        "Image3": "/images/shorts2_2.webp",
        "Image4": "/images/shorts2_3.webp",
    },
    {
        "id": 215,
        "Category": "Shorts",
        "Title": "RICK OWENS",
        "Name": "Black Slivered Denim Skirt",
        "Description": "Lightweight waxed stretch denim skirt." ,
        "Featured":"| Paneled construction" + "| Belt loops" + "| Four-pocket styling" + "| Zip-fly" + "| Frayed edge and distressing at hem" + "Supplier color: Black",
        "Material": "100% cotton",
        "MadeIn": "Made in Italy",
        "Price": 800.00,
        "Image": "/images/shorts3.webp",
        "Image2": "/images/shorts3_1.webp",
        "Image3": "/images/shorts3_2.webp",
        "Image4": "/images/shorts3_3.webp",
    },
    {
        "id": 246,
        "Category": "Shorts",
        "Title": "RICK OWENS",
        "Name": "Black Boxer Shorts",
        "Description": "GOTS-certified organic cotton fleece shorts.",
        "Featured":"| Drawstring at elasticized poplin waistband" + "| Two-pocket styling" + "| Raw edge at cuffs" + "| Vented outseams" + "Supplier color: Black",
        "Material": "Body: 100% organic cotton. Trim: 97% organic cotton, 3% elastane",
        "MadeIn": "Made in Italy",
        "Price": 495.00,
        "Image": "/images/shorts4.webp",
        "Image2": "/images/shorts4_1.webp",
        "Image3": "/images/shorts4_2.webp",
        "Image4": "/images/shorts4_3.webp",
    },
    {
        "id": 251,
        "Category": "Shorts",
        "Title": "RICK OWENS DRKSHDW",
        "Name": "Gray Pods Shorts",
        "Description": "Organic cotton corduroy shorts.",
        "Featured":"| Drawstring at elasticized waistband" + "| Four-pocket styling" + "| Button-fly" + "| Integrated logo-woven webbing strap at interior" + "Supplier color: Hustler blue",
        "Material": "Body: 100% organic cotton. Trim: 97% organic cotton, 3% elastane",
        "MadeIn": "Made in Italy",
        "Price": 550.00,
        "Image": "/images/shorts5.webp",
        "Image2": "/images/shorts5_1.webp",
        "Image3": "/images/shorts5_2.webp",
        "Image4": "/images/shorts5_3.webp",
    },
    {
        "id": 255,
        "Category": "Shorts",
        "Title": "RICK OWENS",
        "Name": "Brown Drawstring Shorts",
        "Description": "Heavyweight GOTS-certified organic cotton jersey shorts.",
        "Featured":"| Drawstring at elasticized waistband" + "| Two-pocket styling" + "| Rolled edge at vented cuffs" + "Supplier color: Brown",
        "Material": "Body: 100% organic cotton",
        "MadeIn": "Made in Italy",
        "Price": 455.00,
        "Image": "/images/shorts6.webp",
        "Image2": "/images/shorts6_1.webp",
        "Image3": "/images/shorts6_2.webp",
        "Image4": "/images/shorts6_3.webp",
    },
];